<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="tracker">

  <xacro:include filename="properties.xacro" />
  <xacro:property name="base_length" value="0.6" />
  <xacro:property name="base_width" value="0.4" />
  <xacro:property name="base_height" value="0.05" />
  <xacro:property name="nose_length" value="0.05" />
  <xacro:property name="nose_radius" value="0.05" />


  <!-- BASE LINK -->
  <link name="world"/>


  <!-- BODY -->
  <link name="px4_uav">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 1 0.8"/>
      </material>
      <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
    </visual>

    <!-- <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
    </collision> -->

   
  </link>

  <link name="nose_uav">
    <visual>
      <geometry>
        <cylinder radius="${nose_radius}" length="${nose_length}" />
      </geometry>
      <material name="red">
        <color rgba="1 0 0 1" />
      </material>
      <origin xyz="0 0 0 " rpy="0 0 0" />
    </visual>
     
  </link>

  
  

  <joint name="world_to_px4_uav" type="fixed">
    <parent link="world"/>
    <child  link="px4_uav"/>
    <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2.0}"/>
  </joint>

  <joint name="px4_uav_to_nose" type="fixed">
    <parent link="px4_uav"/>
    <child link="nose_uav"/>
    <origin xyz="${base_length/2.0 + nose_length/2.0} 0 ${base_height/2.0}"
            rpy="0 0 0"/>
  </joint>



</robot>
